//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeMonthlyPaySlip.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
                  This application outputs a monthly pay slip for a given employee provided their annual salary.

Usage:
    EmployeeMonthyPayslip.exe  GenerateMonthlyPayslip ""EmployeeName"" AnnualSalary

For example - EmployeeMonthyPayslip.exe GenerateMonthlyPayslip ""TestUser"" 60000

Where 
    EmployeeName      : Please provide Employee Name
    AnnualSalary      : Please provide Employee's Annual Salary

Example Output: 

Monthly Payslip for: ""TestUser""
Gross Monthly Income: $5000
Monthly Income Tax: $500
Net Monthly Income: $4500
                ")]
        public string UsagePattern {
            get {
                return ((string)(this["UsagePattern"]));
            }
        }
    }
}
